# Site settings
title: tsuru blog | Open Source cloud application platform
email: 
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: tsurupaas
github_username:  tsuru

# Build settings
markdown: kramdown
